# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_auto_20160612_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
