# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_auto_20160612_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
