# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_auto_20160612_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passWd',
            new_name='password',
        ),
    ]
