# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0010_auto_20160612_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_name', models.CharField(max_length=200)),
                ('url_address', models.CharField(max_length=200)),
                ('url_rank', models.BooleanField(default=1)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
