# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0011_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
