# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0012_url_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
