# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0019_auto_20160612_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date',
            field=models.DateField(blank=True, default=b'2016-06-12'),
        ),
    ]
