# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0021_auto_20160615_0823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day_Data',
            new_name='Daydata',
        ),
    ]
