# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0022_auto_20160615_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydata',
            name='avg_ip',
            field=models.FloatField(default=0),
        ),
    ]
