# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0024_remove_daydata_avg_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydata',
            name='timestamp',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
